// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// extractMolecules
DataFrame extractMolecules(std::string bam_fn, std::string tagname, std::int32_t max_dist);
RcppExport SEXP _gscars_extractMolecules(SEXP bam_fnSEXP, SEXP tagnameSEXP, SEXP max_distSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type bam_fn(bam_fnSEXP);
    Rcpp::traits::input_parameter< std::string >::type tagname(tagnameSEXP);
    Rcpp::traits::input_parameter< std::int32_t >::type max_dist(max_distSEXP);
    rcpp_result_gen = Rcpp::wrap(extractMolecules(bam_fn, tagname, max_dist));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_gscars_extractMolecules", (DL_FUNC) &_gscars_extractMolecules, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_gscars(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
