# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Extract putative DNA molecules from barcoded BAM file.
#'
#' @param bam_fn filename
#' @param tagname barcode tag name
#' @param max_dist maximum distance between reads in a molecule
#' @export
extractMolecules <- function(bam_fn, tagname = "BX", max_dist = 50e4L) {
    .Call('_gscars_extractMolecules', PACKAGE = 'gscars', bam_fn, tagname, max_dist)
}

#' Extract putative DNA molecules from barcoded BAM file.
#'
#' @param inp_file input FQ file
#' @param out_file output counts file
#' @param out_file output counts file
#' @export
countBarcodes <- function(inp_fn, out_fn, wl_fn) {
    .Call('_gscars_countBarcodes', PACKAGE = 'gscars', inp_fn, out_fn, wl_fn)
}

